---
# tasks file for k8s-worker
- name: Join to cluster
  become: yes
  shell: |
    kubeadm join --token $(cat {{ token_path }}) --discovery-token-unsafe-skip-ca-verification 192.168.56.22:6443
  register: output
  args:
    creates: /etc/kubernetes/kubelet.conf
  failed_when: "'Failed' in output.stdout" 