- hosts: all
  become: yes
  pre_tasks:
    - name: Create /etc/ansible/facts.d
      file:
        path: /etc/ansible/facts.d
        state: directory

- name: common features
  hosts: all
  roles:
    - common

- name: installation kubernetes
  hosts: all
  roles:    
    - k8s-base

- name: init cluster
  hosts: master
  roles:
    - k8s-master
    

- name: join worker node
  hosts: worker
  roles: 
    - k8s-worker
    

- hosts: master
  become: yes  
  post_tasks:
    - name: add worker status for node
      shell: kubectl label node worker-node node-role.kubernetes.io/worker=worker
      register: output     
      failed_when: "'Failed' in output.stdout"
      changed_when: no