Vagrant.configure("2") do |config|  
  config.vm.box = "sbeliakou/centos"
  config.vm.box_version = "7.6"

  config.vm.define "master" do |kub|
		kub.vm.network :private_network, ip: "192.168.56.22"
		kub.vm.hostname = "master-node"

		kub.ssh.insert_key = false
		kub.vm.provider "virtualbox" do |vb|
		  vb.name = "master-node"
		  vb.customize ["modifyvm", :id, "--cpuexecutioncap", "30"]
		  vb.memory = "2048"    
  end  
end

	config.vm.define "worker" do |kub1|
	  kub1.vm.network :private_network, ip: "192.168.56.21"
	  kub1.vm.hostname = "worker-node"
	  
	  kub1.ssh.insert_key = false
	  kub1.vm.provider "virtualbox" do |vc|
	    vc.name = "worker-node"
	    vc.customize ["modifyvm", :id, "--cpuexecutioncap", "30"]
	    vc.memory = "2048"   

	  kub1.vm.provision :ansible do |ansible|
        ansible.limit = "all"
        ansible.playbook = "playbook.yml"
        ansible.inventory_path = "./inventory"
        ansible.raw_arguments  = [
"--connection=paramiko"]
  end  
end
end
end
